[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ymdm"
version = "0.1.0"
description = "YouTube Music Download Manager"
requires-python = ">=3.10"
dependencies = [
    "yt-dlp",
    "ytmusicapi",
    "mutagen",
    "rich",
    "textual",
    "click",
]

[project.scripts]
ymdm-gtk = "ymdm.gtk.main:run"
ymdm = "ymdm.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["ymdm*"]

[project.optional-dependencies]
desktop = ["pygobject>=3.48.0"]
